# MoveStraightIn2D.action from https://ros2-tutorial.readthedocs.io
# Attempts to move from initial position to `desired_position`.
# Returns `final_position` achieved.
# Feedback is the Euclidean distance between `initial_position` and the current position.
geometry_msgs/Point desired_position
---
geometry_msgs/Point final_position
---
float32 distance