services:
  talker:
    image: murilomarinho/sas:jazzy
    stop_signal: SIGINT
    stop_grace_period: 10s
    environment:
      - ROS_DOMAIN_ID
    command: /bin/bash -c "
      ros2 run demo_nodes_cpp talker
      "

  listener:
    image: murilomarinho/sas:jazzy
    stop_signal: SIGINT
    stop_grace_period: 10s
    environment:
      - ROS_DOMAIN_ID
    command: /bin/bash -c "
      ros2 topic echo /chatter
      "
